on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Integrate vcpkg
      run: vcpkg integrate install
    - name: Build SteelYourself
      run: msbuild ./SteelYourself/SteelYourself.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Upload SteelYourself
      uses: actions/upload-artifact@v2
      with:
        name: SteelYourself
        path: ./SteelYourself/x64/Release/SteelYourself.dll
