on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build SteelYourself
      run: msbuild ./SteelYourself/SteelYourself.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Upload SteelYourself
      uses: actions/upload-artifact@v2
      with:
        name: SteelYourself
        path: ./SteelYourself/x64/Release/SteelYourself.dll

    - name: Build TextureSwapper
      run: msbuild ./TextureSwapper/TextureSwapper.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Upload TextureSwapper
      uses: actions/upload-artifact@v2
      with:
        name: TextureSwapper
        path: ./TextureSwapper/x64/Release/TextureSwapper.dll

    - name: Build PermanentWinds
      run: msbuild ./PermanentWinds/PermanentWinds.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Upload PermanentWinds
      uses: actions/upload-artifact@v2
      with:
        name: PermanentWinds
        path: ./PermanentWinds/x64/Release/PermanentWinds.dll

    - name: Build PlayerColorChanger
      run: msbuild ./PlayerColorChanger/PlayerColorChanger.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Upload PlayerColorChanger
      uses: actions/upload-artifact@v2
      with:
        name: PermanentWinds
        path: ./PlayerColorChanger/x64/Release/PlayerColorChanger.dll

